<?php

namespace BusinessBundle\Repository;

/**
 * approvalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class approvalRepository extends \Doctrine\ORM\EntityRepository
{
}
