<?php

namespace BusinessBundle\Repository;

/**
 * VisitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitsRepository extends \Doctrine\ORM\EntityRepository
{
}
